[package]
name = "wasm_converter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hex = "0.4"
kmip-ttlv = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2" # Para interagir com o JS
